name: Github Pages mkdocs gh-deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: mkdocs gh-deploy --verbose
